baseURL = 'https://mayorobadji.github.io/diama-blog/'
languageCode = 'en-us'
title = 'DiaMa Blog'
theme = 'PaperMod'

canonifyURLs = true
relativeURLs = true

[params]
author = "Meilo & Meila"
description = "Blogs/Posts about our IT journey"
EOF
